### ISSUE TITLE
Add initial dashboard page sidebar content

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#103]
I'd love to add a marketing/onboarding/education block in our UI, probably on the main dashboard page. I couple examples I like:

- Stripe has a small banner ad sized element that they use for new feature promotion. I think we could easily author something similar, but perhaps more in HTML. A background image draws in attention here, which I really like
- GitHub has this:

![image](https://user-images.githubusercontent.com/1140183/168120254-0d5fd97a-050f-4c4a-8e62-9c76e8c0c378.png)

It's blog post then changelog specifically. Not just blog posts. I'd probably lean towards specific user features instead of just changelog though. We don't summarize changelogs anyways.

**Comment by agjohnson** [comment]
This is a good issue to jump into @humitos I'm throwing it your way.

I noted some options, and the commercial sidebar has some placeholder content for creating an organization (this is not a good fit here).

**Comment by humitos** [comment]
With this code:

```html
        <div class="ui card">
          <div class="image">
            <img src="https://about.readthedocs.com/images/read-the-docs-loves-ruby.jpg">
          </div>
          <div class="content">
            <a class="header" target="_blank" href="https://about.readthedocs.com/blog/2024/03/read-the-docs-loves-ruby/">Read the Docs ❤️ Ruby</a>
            <div class="description">
              We are happy to announce support for Ruby is now available as an option as pre-defined building tools (<code>build.tools</code>).
              Ruby is now officially supported to build project documentation on Read the Docs 🎉
            </div>
          </div>
        </div>
```

I was able to generate the following:

![Screenshot_2024-04-15_12-00-57](https://github.com/readthedocs/ext-theme/assets/244656/e9a7076f-307c-4221-a1c7-21ac0d5a4470)


From here, I think we can create a small HTML template that renders data from the database:

* show only one at a time
* add a small X to close the card and save a cookie to not show it again to the same user
* expect `image` (optional), `link`, `header` and `description`
```python
class DashboardPromotion(TimeStampedModel):
  image = models.ImageField()
  link = models.URLField()
  header = models.CharFiedl()
  description = models.TextField()
  expires = models.DateField()   # when stop showing this promotion
```

Then we can simply manage these promotions from the Django Admin, without building a UI or similar.

@agjohnson what do you think about this approach?

**Comment by agjohnson** [comment]
I could see us using database driven content, but would also say that seems like a step for a bit later. I don't yet see us needing a faster way of updating this content and we instead probably benefit the most from a few different sizes and shapes of content here. I'd like to see a mix of content here.

On the layout side of things, I would avoid the blog post style of throwaway image + title + excerpt for now. It takes up a lot of space and feels like the content should be very important because of this.

For anything really important, I'd sooner use an image ad instead -- that is, a background image with text overlay. It's compact but still offers visual content. I mentioned above the Stripe ads they included in their dashboard but can't find a good example of this anymore. Creating ads would be an extra step either way, so maybe this is a future addition too anyways.

On the content side, I'm not sure if you meant to promote a blog post intentionally, but this sort of content feels lowish priority. Linking blog posts are great for awareness, but many of our posts don't apply to many of our users either.

We can give the user content that is directly applicable to them by promoting onboarding steps and features the user should be using. This was in my examples above, adding cards calling out features directly. These are probably all conditional sort of blocks, depending on what the user has already configured:

  - Enable PR builds
  - Enable GitHub SSO
  - Invite members to your organization
  - Host multiple versions
  - Try Addons/custom build commands/new build tools 

I'd still stick with text only unless we really want to draw user attention to something. Conditional content would be another point against keeping this in the database for now though.

But, a blog post feed seems like great content still but something that can be lower on the sidebar. I think I like the GitHub example above -- just titles and dates, no excerpts/images. Frankly maybe eventually we just poll the RSS feed so we never have to update this manually. I think we can manually link posts for now even.

**Comment by humitos** [comment]
> We can give the user content that is directly applicable to them by promoting onboarding steps and features the user should be using. This was in my examples above, adding cards calling out features directly. These are probably all conditional sort of blocks, depending on what the user has already configured

👍🏼 

> a blog post feed seems like great content still but something that can be lower on the sidebar. I think I like the GitHub example above -- just titles and dates, no excerpts/images. Frankly maybe eventually we just poll the RSS feed so we never have to update this manually

👍🏼 

----

I'm fine starting with these two before going data driven.
