### ISSUE TITLE
Better experience when many projects are available to import

### ISSUE THREAD

**Issue by takluyver** [readthedocs/ext-theme#13]
I like the 'import project' design introduced in readthedocs/readthedocs.org#1695 overall, but the pagination is annoying me. I'm in several organisations with many repositories, and as my username is relatively late in the alphabet, I have to click through many pages to get to my own personal repos.

How could this be better:
- I can filter down to an organisation's repos easily, but not to my own personal repos (takluyver/foo). I guess this would be simple to add.
- Put a search box on the import project page, preferably with search-as-you-type.
- Sort recently updated repos to the top, like Github's [repo view](https://github.com/takluyver?tab=repositories), as they're the ones I'm most likely to want to use. I'm baffled by the sort order at the moment - it seems mostly alphabetical, with some things scattered randomly into it.

**Comment by blombergedvin** [comment]
Want to give this issue a bump :) 
I believe we have at least 150 pages of projects in my organisation, and importing a project at the end takes more than 10 minutes of clicking next. 

A search would be ideal (either a "begins with" or contain would work). 
Another alternative would be to allow you to jump to a specific page in the pagination, either in the UI or reflect the current page in the URL.

**Comment by humitos** [comment]
@blombergedvin can you give it a try to our new beta dashboard at https://beta.readthedocs.org/ and let us know if the UX for importing a project has improved? 😄

**Comment by blombergedvin** [comment]
@humitos Exciting! I was not able to login with my normal username/email, even though the same works in the old dashboard. 
Get a: `Error
The username and/or password you specified are not correct.`.

**Comment by humitos** [comment]
@blombergedvin that's pretty weird -- the db is exactly the same, so if you are able to login on readthedocs.org, you should be able to login with the same user/pass in beta.readthedocs.org

By the way, are you referring to the "old dashboard" to the community (readthedocs.org) or the business version (readthedocs.com)?

**Comment by blombergedvin** [comment]
@humitos That is probably the reason. I'm using the business version with https://readthedocs.com. Didn't notice the slight difference in the url.
Is there a beta dashboard for the business version as well?

**Comment by humitos** [comment]
> Is there a beta dashboard for the business version as well?

Not yet, but we are working on it. Hopefully, we will publish a beta version for the business version soon.

**Comment by agjohnson** [comment]
I think this issue can be closed, as the new dashboard resolves this. I'll removed this from the dashboard roadmap at least, as it's been long solved there.
