### ISSUE TITLE
Advanced settings: Remove "default settings"

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#159]
We have had several users being confused about their projects using a config file and then changing the settings from the web UI, and being surprised that they don't take effect. Just after we tell them that there is a warning about this, they realize about it.

![Screenshot 2023-04-10 at 14-43-37 docs - Advanced Settings - Read the Docs](https://user-images.githubusercontent.com/4975310/230984860-0ba75827-1645-4339-b11a-ba6094a1dcc1.png)

I think it's probably worth making that an actual warning by making red/yellow.

Page: https://beta.readthedocs.org/dashboard/docs/advanced/
Code: https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/templates/projects/project_advanced_settings_helptext.html

**Comment by humitos** [comment]
> A couple more notes though:

I wouldn't invest this time here and just remove the form. We've given people months to make this migration and they can always find the combination of configuration that suit their needs by reading the documentation.

**Comment by agjohnson** [comment]
Well, while it may be the case that the user has had time to switch, but I wouldn't punish the user here either. Removing the form would be fairly hostile UX, as I'm sure some users would need to reference the settings they were previously using. We can avoid all of that by just applying the `disabled` class on the form element or fieldset, making these fields and the whole form read only.

**Comment by humitos** [comment]
> Well, while it may be the case that the user has had time to switch, but I wouldn't punish the user here either. Removing the form would be fairly hostile UX, as I'm sure some users would need to reference the settings they were previously using

How much time would be an acceptable time for this migration? Can we set a date for removal?

**Comment by agjohnson** [comment]
Yeah, let's definitely set removal for a month later or something. If projects haven't dealt with the upgrade through one of the brownouts, and doesn't deal with their project until after the final deprecation and their builds are stuck failing, it's not a very active project.

I think a month or two is a generous grace period. After that, it would really only be very inactive projects that might hit trouble with settings.

**Comment by humitos** [comment]
I opened two PRs to move forward with this because I want to keep simplifying our product and avoid confusions:

* https://github.com/readthedocs/readthedocs.org/pull/11036
* https://github.com/readthedocs/ext-theme/pull/263
