### ISSUE TITLE
Addons: allow users to opt-in into the new addons

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#212]
We have deployed the new addons for projects using `build.commands` and it has been working fine. We haven't received any complain and I've already saw users jumping into `build.commands` _because_ they have the flyout there as well (see https://github.com/readthedocs/readthedocs.org/issues/10706)

Also, we've found a way to "migrate old projects/builds using the old integrations to the new one" dynamically using a Cloudflare Worker (see https://github.com/readthedocs/readthedocs-ops/pull/1402).

However, _we can't do this migration automatically for all the projects_ because it won't look exactly the same. We will be moving the flyout from the bottom left being integrated into the navbar, to the bottom right being fixed in a floating position. I created an issue in the theme to make this integration to look exactly the same at https://github.com/readthedocs/sphinx_rtd_theme/issues/1523 -- but it needs a non-trivial amount of work for that to define the exact addons API, work on JS/CSS, release a new version, wait for people to migrate to this version, etc.

We can follow a simpler path here: "allow users to opt-in into the new addons". When opt-in we can communicate these differences (look&feel changes and extra features) and they can disable if they don't like it. This will give users the features we already have in the new addons immediately to them, it will allow us to gradually roll this out and fix issues as we go and also give us feedback about that integration into the theme should be.

Related:
* https://github.com/readthedocs/ext-theme/issues/211
* https://github.com/readthedocs/readthedocs-ops/pull/1402
* https://github.com/readthedocs/sphinx_rtd_theme/issues/1523

**Comment by agjohnson** [comment]
For assignment, I'm happy to help with the ext-theme changes, but they will also be very small to start, and mostly just duplicating existing templates. @humitos would you like to start with the form/view/url additions here first? I've assigned us both for now, but it might be easy enough to add all at once too.

**Comment by humitos** [comment]
I see two different approaches here:

1. add a `Project.force_addons_enabled (bool)` with a simple project's form that only exposes that field and template that shows it
2. add a `Projects.addons (foreign key)` to a new model `AddonsConfig` that contains all the configs for each addon. Then we create one `Form` per addon

**Comment by humitos** [comment]
I went ahead and opened https://github.com/readthedocs/readthedocs.org/pull/10733 and https://github.com/readthedocs/ext-theme/pull/213

**Comment by agjohnson** [comment]
> add a Project.force_addons_enabled (bool) with a simple project's form that only exposes that field and template that shows it

This sounds like what we are wanting immediately, for this issue -- just the beta opt in/out.

> add a Projects.addons (foreign key) to a new model AddonsConfig that contains all the configs for each addon. Then we create one Form per addon

And this sounds like the continuation of this work that we'll want for #211. Or we can continue thinking how we'll lay this out in code more, I don't have strong opinions on the modeling structure.

Does that match what you're thinking too?

**Comment by humitos** [comment]
Yeah, but I went ahead already and implemented both of them: the immediate requirement (enable/disable beta addons) and the underlying modeling needed to allow users customize the addons --which is currently not exposed to users yet.
