### ISSUE TITLE
NoReverseMatch `/projects/{project_slug}/builds/`

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#251]
For background see: https://read-the-docs.sentry.io/issues/4721864482/

**Comment by humitos** [comment]
I just hit this at https://beta.readthedocs.org/projects/argilla-docs/builds/ as well. The sentry issue is at https://read-the-docs.sentry.io/issues/4721864482/events/0d77827f2fb947f18d127dcc62aadf8f/

**Comment by agjohnson** [comment]
I'm a little confused by this one, it's not clear what scenario this can even happen in. Based on the stack trace, the problem is this template block:

https://github.com/readthedocs/ext-theme/blob/add9c4d96d6f8b3647603798440858cb008738e5/readthedocsext/theme/templates/includes/elements/chips/version.html#L6

![Image](https://github.com/readthedocs/ext-theme/assets/1140183/2f104a1a-6415-496c-9ae5-4a74367017db)



However, this implies that `version.project.slug` and `version.slug` are both null strings? 😕

**Comment by agjohnson** [comment]
It was `Build.version` that was null. If we clean these up that explains why I can't reproduce this one ever too. I was able to manually set this up locally and found the issue.
