### ISSUE TITLE
SSO authed users spammed with sign in notifications

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#258]
Honestly, I'm not sure where this is coming from or why. To reproduce:

- Log in to beta.readthedocs.com with GitHub user `readthedocs-sso-2`
- Navigate to multiple pages
- Each page load you'll git a repeated toast notification "Successfully signed in"

[Screencast from 2023-12-20 19-15-43.webm](https://github.com/readthedocs/ext-theme/assets/1140183/679a913b-564c-414c-a36e-737bdb9d9c29)

This comes from Django messages template code, so wouldn't involve JS to clear the notification. It's the only notification I noticed this with.

**Comment by humitos** [comment]
Hrm... I can't reproduce this with my own GH user. I only see this notification once when I sign in.

**Comment by agjohnson** [comment]
This was only happening for the `readthedocs-sso-2` user, it wasn't happening on my normal user or the `readthedocs-sso-1` GitHub account.

I'm guessing this was maybe related to the GitHub organization/team membership. The `readthedocs-sso-2` user was removed from the GitHub org/team. I can't reproduce this one now, I only get one notification logging in with the `readthedocs-sso`, so I suspect that probably was the cause.
