### ISSUE TITLE
Add missing notification template blocks for user, project, organization notifications

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#260]
From the deploy today, it seems these were not ported to the new dashboard.

**Comment by humitos** [comment]
> Organization: ??? -- I think this was not implemented there.

I implemented this at https://github.com/readthedocs/readthedocs.org/pull/11023

**Comment by agjohnson** [comment]
We might have missed opening an issue for the organization notifications, I remember discussing it at some point.

For notifications for user/project/orgs on the new dashboard, you can copy the previous template HTML structure for the message-extends messages. I believe this was removed in that last PR.
