### ISSUE TITLE
Remove "sponsored" footer on Commercial

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/ext-theme#264]
Realized we have the "sponsored by" content in the footer on the commercial side. Would be good to have a flag where we can only show this on community.

**Comment by humitos** [comment]
I'm not sure how we are differentiating community from commercial templates. I didn't find these differentiation in the repository, but I assume we could just remove the `footer_sponsors` block in commercial ones:

https://github.com/readthedocs/ext-theme/blob/8889fae8459927ca924f24b160e6d8f0d54788b5/readthedocsext/theme/templates/includes/footer.html#L133-L136

**Comment by ericholscher** [comment]
Yea, @agjohnson is there a pattern here for this?

**Comment by agjohnson** [comment]
In other contexts, `USE_ORGANIZATIONS` makes sense, though less so here. I would just reuse that context variable for now, ie:

https://github.com/readthedocs/ext-theme/blob/d866730bfad4636921c6970bed3931ae4a3441a7/readthedocsext/theme/templates/includes/header.html#L69

**Comment by ericholscher** [comment]
Cool, I used `USE_PROMOS`, since hopefully we'll get ORGANIZATIONS on .com before we ship ads on it 😆

**Comment by humitos** [comment]
At this point, I think we should have a `ON_READTHEDOCS_COMMUNITY` and/or `ON_READTHEDOCS_BUSINESS` instead of using settings that were meant for different purposes 😄

**Comment by ericholscher** [comment]
@humitos Yea. I think we have `PRODUCTION_DOMAIN == 'readthedocs.org'`, which is probably what we actually want? Though we could always just have another value in our context processor that precomputed that :D
