### ISSUE TITLE
Build details page: match colors for cancelled builds

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#269]
I like that you used a different color (🟧 ) for commands that output with the custom exit code.

![Screenshot_2024-01-10_16-59-26](https://github.com/readthedocs/ext-theme/assets/244656/ed2f811b-bfa7-4d83-b13d-cedd9c500eed)

Now, the build is not exactly failed. Would it make sense to mark is as cancelled instead?
as we are doing in https://beta.readthedocs.org/projects/dev/builds/23063631/ for example

![Screenshot_2024-01-10_17-01-49](https://github.com/readthedocs/ext-theme/assets/244656/25336e1e-6e8d-422d-991b-89607e832856)

_(opened from a [conversation in Slack](https://readthedocs.slack.com/archives/C029M3W01KR/p1704902426628959))_

----

It seems the logic to distinguish this is implemented in the front-end because the backend does not return what's expected:

https://github.com/readthedocs/ext-theme/blob/a39cec9063a82d55e1a549f914d14c90dbb2e506/src/js/build/detail.js#L249-L301

**Comment by humitos** [comment]
I think I found the issue.

The new notification system does not use populate `Build.error` anymore, so this check is not accurate here since `this.error()` will always be empty: 
https://github.com/readthedocs/ext-theme/blob/178a684b281c221f0fd608cf3e44fa1f32130fff/src/js/build/detail.js#L273

**Comment by agjohnson** [comment]
I believe this is similar to the backend bug at:

- https://github.com/readthedocs/readthedocs.org/issues/11170

With that bug fixed, the UI looks correct to me now when cancelling builds manually:

![image](https://github.com/readthedocs/ext-theme/assets/1140183/8235b272-8aa7-4e05-b17d-d968cb91737a)

> Would it make sense to mark is as cancelled instead?

Yeah exactly. For this UI to show builds cancelled by the 183 exit code, the backend should set the build state to cancelled. The front end should already have the correct logic to support this state, but if not we can reopen this.

I opened this to address the backend change:

- https://github.com/readthedocs/readthedocs.org/issues/11232
