### ISSUE TITLE
Integrations: convert long data fields to input elements

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#294]
On the integration detail view, we show a secret that can be quite long:

![image](https://github.com/readthedocs/ext-theme/assets/1140183/ea77ac82-53c8-40ba-b383-d1c289c245f9)

In other views, this would be in an input field with a copy button. This is a nicer look and the copy button is really helpful. The organization invite UI is one that comes to mind, but there are a few views that use this pattern

**Comment by stsewd** [comment]
Long secrets are for old integrations (due to a bug), new secrets are shorter.

**Comment by agjohnson** [comment]
Maybe look at docs project or another older project. I don't have a URL handy for this.

**Comment by humitos** [comment]
Example page showing this issue: https://app.readthedocs.org/dashboard/docs/integrations/148415/
