### ISSUE TITLE
Add plausible to dashboard

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#301]
It would be helpful to monitor usage in both the users starting to use the beta and the users that are opting out of the beta. This can probably mostly be inferred with just adding Plausible on the beta dashboard and settings a few specific goals. A few notes here

- Track referrer when getting a new user signup on beta. What application view (not URL) did the user come from?
- Track users that are clicking a link to go back to the legacy dashboard. What view did this occur on?
- It would be most helpful to see the split in traffic between the beta dashboard and the legacy dashboard. This would take using the same analytics on both sites.

----

- [x] Set up Plausible for beta.readthedocs.org and beta.readthedocs.com
- [x] Copy Plausible inection from website

**Comment by agjohnson** [comment]
Huh. I had started to add this last week. Now when I log in I get this:



![Image](https://github.com/readthedocs/ext-theme/assets/1140183/aa493608-3721-4901-b433-d703abd4d708)

I can't tell why we have to upgrade though 🤷

**Comment by ericholscher** [comment]
Loads fine for me? 🤷

**Comment by agjohnson** [comment]
Yeah I feel we hit this in the past too. I haven't started doing anything with the site I created, so feel free to drop it or whatever. Or should I try inviting you maybe?

**Comment by agjohnson** [comment]
Invite didn't work, I've tried to transfer ownership. If this doesn't work I'll delete and let you start creation instead. We need a beta.readthedocs.org and beta.readthedocs.com.

**Comment by ericholscher** [comment]
I accepted the transfer, and created a second domain, and invited you to it.

**Comment by humitos** [comment]
BTW, I don't have access to those new `beta.` sites 😄

**Comment by agjohnson** [comment]
@humitos this is what my dashboard looks like, in case you are missing others: 
![image](https://github.com/readthedocs/ext-theme/assets/1140183/fbc2ba17-dcbd-4bb5-b362-fc6b68ece7cd)

**Comment by humitos** [comment]
Cool thanks! Yeah, that's how mine looks like too 👍🏼
