### ISSUE TITLE
Pages: add documentation/user error pages

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#304]
From #295, I'm considering the doc/user error pages separate work to help isolate the work more. Relevant conversation here:

- There are multiple versions of the 404 page, and some features we might want to bring forward into the new dashboard.
- The new dashboard loads a number of assets and one of the things I expect to hit is the bug where the URLs and assets aren't defined on the instance that is serving the 404 page. We have a few bugs here in the past, and it's one of the reasons our error pages are more empty now.
- But a large looming issue is that the error pages we show are going to be more heavily branded like our application, which is an odd fit for user documentation sites. Our CAS/etc login for documentation views should be super minimal. This is a later problem, but defining it for now.

----

- [x] Make Proxito use the ext-theme templates: https://github.com/readthedocs/common/pull/220
- [x] Documentation error templates should be isolated from application error templates and should not extend from the application templates at all -- to avoid contaminating the template rendering with application URLs etc
- [x] Proxito error page features could use tuning
- [x] Proxito error page copy could also use tuning and reduction
- [x] Consolidate error templates under single path and pattern
  - [x] `errors/404/*.html`
  - [x] `core/teapot.html`
  - [x] `401.html`
  - [x] `/spam.html` and proxito view
- [x] Proxito should have tuned 500/401 templates, as the dashboard error templates raise exceptions about missing URLs/etc.
- [x] Proxito error templates shouldn't use icons, as we can't whitelist every single hosted domain with our Font Awesome kit.

**Comment by agjohnson** [comment]
I'm running into a lot of complexity with the proxito errors that are making this work fairly complicated.

I believe I will be breaking this work up into a few chunks:

- Split out Proxito templates for base errors on the application -- 401/500/etc, as the dashboard templates include URLs that can't resolve in the header/footer/etc. Proxito can't render the existing 500/etc error templates because they include URLs in header/footer/etc that proxito doesn't have.
- Next step, create a base style for proxito error messages using the new template paths. I mentioned these won't look the same, but found there are lower level issues that prevent porting the dashboard error templates to proxito [^1][^2]
- Do something with contextualized error messages. I am going to probably remove most of the features and avoid this complexity of these pages to start. More discussion in https://github.com/readthedocs/readthedocs.org/issues/11486

[^1]: We can't use icons. The hosted icon kit limits the kit usage by domain name, so custom domains and project sub domains aren't supported.
[^2]: Our application JS interferes with addons JS, and some conflicts in custom elements exist already, like `readthedocs-notification`.

**Comment by agjohnson** [comment]
I'm leaning towards a very minimal error page, which might leave the door open to easier customization. But avoiding looking like the dashboard is my main need right now:



![Image](https://github.com/user-attachments/assets/87b00133-d8c5-4ebe-b513-19f67e49e42c)

**Comment by humitos** [comment]
A minimal page like the example looks great to me. I'd probably remove the paragraph that starts with "In the past..." from the section "The host _nginx_ is unknown on Read the Docs" since that information is dated and I don't think there should be any project hitting that issue anymore.

Also, I think that "Admin" is now called "Settings" in the new dashboard.

**Comment by agjohnson** [comment]
Yeah, agreed! All of that copy needs to be updated and trimmed down. This content all provided by the contextual 404 templates (`errros/404/`) and I'll be tuning this next. If this content poses any problems, it's probably worth coming back to even as this content feels more like a liability than valuable. I think trimmed down they might be okay though.

The main part I'm working on right now is the structure and look/feel of these pages, but I'm also liking the direction here. I'll have a draft PR today probably.
