### ISSUE TITLE
Build details page on mobile

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#308]
Opening a build details page on mobile doesn't render properly: https://beta.readthedocs.org/projects/test-builds/builds/23655124/

![Screenshot_20240314-114241](https://github.com/readthedocs/ext-theme/assets/244656/797199b7-e17a-492a-81ac-754c67e7b86b)

It seems that all the commands are expanded by default and theirs content is not wrapped.

**Comment by agjohnson** [comment]
It actually seems to be the text menu before the output pane that is triggering the wide viewport. Stacking that menu reflows the UI as I would expect on mobile.
