### ISSUE TITLE
Login: view style fixes

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#312]
- [x] From #307 we probably want a wider view on the form now
- [x] Support three log in options better, it's a bit cramped
- [x] Fix floating on remember me checkbox
- [x] Fix casing on remember me checkbox
- [x] Fix button floating, should be right floated
- [x] Make tabs more obvious, or make tab copy more obvious that these are all log in methods
- [x] #330
- [x] Reduce visual importance of 'forgot password'
- [x] Errors on login email form stopped showing (bad password/etc)
- [x] Increase distinction between a regular user/password from shared by password (see https://github.com/readthedocs/readthedocs-corporate/issues/647)

**Comment by agjohnson** [comment]
> Increase distinction between a regular user/password from shared by password

I'm not quite sure what to do with this one, so I'm inclined to call this fine. The source issue seems to reference prose copy on the login form that does not exist anymore.

**Comment by humitos** [comment]
Looks good for now to me 👍

**Comment by agjohnson** [comment]
I'm sure we might want to tune this later too. "Password" and "Email" are still overlap a bit.
