### ISSUE TITLE
Build: rebuild button should include build_pk in POST

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#336]
At least for PR builds, the rebuild button needs to send over the build_pk as well. Normal versions seem to rebuild fine, but PR builds give a 404 response when the build_pk is missing from the post. Or at least this is the only difference I spot between the beta and legacy dashboards currently, there could be something else happening here.

**Comment by agjohnson** [comment]
I found out why this is awkward. It is because there are two different "retry" methods used here. For external versions, we evaluate `Build.can_rebuild`. This is only true for external versions though. For non-external versions, aren't retrying a Build instance but instead create a new Build.

**Comment by agjohnson** [comment]
I finally got set up to test with pull request builds locally. My change does indeed trigger a new build on PR builds, but this shows up as a new build entirely and does not update the existing pull request (at least on GitLab, there is no new pipeline created).

I am starting the new build through APIv3 and the build create endpoint.

To recap what is happening:

- BuildTriggerMixin has different logic than our APIv3 endpoint.
- The project detail view and build list view extend the BuildTriggerMixin and accept posts to these views as hidden forms on these views.

I suspect the best change is using the same code in our APIv3 endpoint as the BuildTriggerMixin, so that we can build PR versions as well.

**Comment by humitos** [comment]
I'm not sure I'm understanding correctly here, but we should _always_ create a new Build object when triggering a new build, no matter what type of version the build is attached to (branch, tag or external)

**Comment by agjohnson** [comment]
I thought the external version rebuild _reused_ the last build, but it only uses the last build to get the commit to rebuild.

**Comment by humitos** [comment]
> but it only uses the last build to get the commit to rebuild

When rebuilding a version, we don't need to grab the commit used at the time the version was built. We should always build using _the latest_ commit for that version. Rebuilding a version using a fixed commit will be pretty confusing and it's not the feature we want to expose to users.

If we were using that before, it's the wrong behavior and it's a bug.

**Comment by agjohnson** [comment]
When rebuilding an _external version_ we do need to use the latest commit, I'm not describing rebuilding standard versions above. This logic comes directly from existing code:

https://github.com/readthedocs/readthedocs.org/blob/488d50dc4239d3d73ccf9d142f009714ebc95e82/readthedocs/builds/views.py#L58-L82
