### ISSUE TITLE
Fix or remove embed topics

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#34]
Unfortunately, with embed API v3, data that this feature relied on was removed from the API. This feature is throwing errors on a lot of pages, where no document id was provided or found.

The v2 API is deprecated and v3 doesn't support our use case, though we did discuss implementing this as a separate feature. We need to have this discussion first.

**Comment by benjaoming** [comment]
Is there more to be done to fix this issue than what https://github.com/readthedocs/ext-theme/pull/168 proposes?

If JS files can remain untouched, it should be enough to simply replace all usage of the embed docs JS with hard-coded HTML?

**Comment by agjohnson** [comment]
I don't think there is much more to do here, I just found this issue was unassigned.
