### ISSUE TITLE
Invited pending maintainers do not appear

### ISSUE THREAD

**Issue by stevepiercy** [readthedocs/ext-theme#352]
See related readthedocs/ext-theme#353

## Details

When I use the standard Dashboard version at:

https://readthedocs.org/dashboard/volto/users/

...then I am able to see pending maintainers to whom I have sent an invitation but have not yet accepted.

These invitees do not appear in the RTD Beta Dashboard at:

https://beta.readthedocs.org/dashboard/volto/edit/

## Expected Result

Invited pending maintainers should appear in the Beta Dashboard.

## Actual Result

Invited pending maintainers do not appear in the Beta Dashboard.

**Comment by agjohnson** [comment]
Odd, not sure why this would be the case as pending invites do show in the maintainers list normally:

![image](https://github.com/readthedocs/ext-theme/assets/1140183/38a733d5-2c40-4582-bee8-7b906d9fa093)

**Comment by stevepiercy** [comment]
Pending invitations for maintainers now show up in the Beta Dashboard.

Was there a recent release?

Is there a delay between adding a maintainer in the original dashboard (due to issue #353) and it showing up in the Beta dashboard?

**Comment by agjohnson** [comment]
Odd. There should not be a delay, no. I just tested this and was able to invite a member by username to a project and the invite showed immediately on both dashboards. Same for revoking, it was all instantaneous.

We release weekly, but there haven't been any changes to this listing or the modeling for it in a while.

**Comment by stevepiercy** [comment]
OK, I'll close this as can't reproduce. Thanks for checking.

**Comment by stevepiercy** [comment]
Bah, I guess I can't undo that mistake entirely. Sorry for messing up your Roadmap stats.

**Comment by agjohnson** [comment]
Hah, no worries :smile: I still can't come up with a good reason why this would have happened, so if you notice it again, feel free to reopen this. Perhaps we're missing something in testing this
