### ISSUE TITLE
Teams: invites on team cause exception in AdminPermission

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#354]
Hitting https://beta.readthedocs.com/organizations/read-the-docs-qa/teams/qa/ returns 500 to me.

Sentry issue: https://read-the-docs.sentry.io/issues/5389496991/?project=161479&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by agjohnson** [comment]
It seems the issue here is not editing the team, but just viewing and only *this particular team*. Specifically, this is on the view listing the members of the QA team.

https://beta.readthedocs.com/organizations/read-the-docs-qa/teams/qa-user-auth/ does not show this error.

**Comment by agjohnson** [comment]
I can fix this in templates, but I would consider this a bug in community instead. `Team` should be supported by `AdminPermissionBase.admins()`.

**Comment by agjohnson** [comment]
Fixed at:

- https://github.com/readthedocs/readthedocs-corporate/pull/1793
- https://github.com/readthedocs/readthedocs.org/pull/11351
