### ISSUE TITLE
Notifications: cancelled notifications are shown for organizations

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#359]
It seems we are listing _all the notifications_ for organization, even those that are already `cancelled`:

https://github.com/readthedocs/ext-theme/blob/d758c66ed0d4cce607e7405a3e2cb8e216f15ff8/readthedocsext/theme/templates/organizations/partials/header.html#L16-L22

Also, it seems that we are using a different approach for organizations than for projects:

https://github.com/readthedocs/ext-theme/blob/d758c66ed0d4cce607e7405a3e2cb8e216f15ff8/readthedocsext/theme/templates/projects/base.html#L8-L14

Should we port the notifications for organization to the `readthedocs-notification-list` pattern?

**Comment by agjohnson** [comment]
Yeah this should use the same API pattern, not sure why it doesn't already
