### ISSUE TITLE
Build listing version filtering doesn't work anymore

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#386]
1. go to the versions
2. click on one of them
3. it should show the builds for that particular version

However, it shows the builds for all the versions.

![Peek 2024-06-17 16-29](https://github.com/readthedocs/ext-theme/assets/244656/64615e27-a562-4829-8f7c-625d2648d431)

**Comment by agjohnson** [comment]
Guessing this is the query param name changed or something.
