### ISSUE TITLE
Build popup should be smaller and have more padding when loading

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#389]
This is a pretty minor issue.

I noticed the popup shown when hovering on a build shows a spinner icon that I think it would look better by reducing the width of it and increasing the padding for the icon so it doesn't touch the borders.

![Peek 2024-06-19 13-51](https://github.com/readthedocs/ext-theme/assets/244656/b34b2d63-de62-4d9c-83d7-332548ffb22e)

**Comment by agjohnson** [comment]
Note, this is going to be for all of the popupcards, most especially any doing async API interactions on hover.
