### ISSUE TITLE
Gold view templates uses inline JS

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#407]
We should probably just handle everything from Stripe instead of embedding stripe into our site.

https://github.com/readthedocs/ext-theme/blob/846d19484eb2972f80365cb48d3ac53b935815b0/readthedocsext/theme/templates/gold/subscription_form.html#L22-L35

I'll probably add a specific rule for this view to our CSP header.

**Comment by agjohnson** [comment]
I either punted on this UI completely, and this is broken currently, or this is just an orphaned template/block that isn't used. Very agreed we shouldn't be doing this either way though.

**Comment by agjohnson** [comment]
I definitely punted on this template completely, it's very broken at the moment. I'll work on porting this over and reusing the Stripe code we already have, not reusing the old payment form pattern.

**Comment by humitos** [comment]
It seems that we should delete `subscription_form.html` file, right?

**Comment by humitos** [comment]
I saw that we are deleting it inhttps://github.com/readthedocs/ext-theme/issues/407
