### ISSUE TITLE
`NoReverseMatch` when hitting builds listing page

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#412]
Go to https://app.readthedocs.org/projects/pycampes/builds/ and/or https://app.readthedocs.org/projects/pygsp2/builds/ and you will get a 500.

Sentry error: https://read-the-docs.sentry.io/issues/5564576585/

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_11t9zb)

**Comment by humitos** [comment]
This happens at this line https://github.com/readthedocs/ext-theme/blob/bbff088c5b1edd13d15c52b1b348ec1dc7c5265c/readthedocsext/theme/templates/builds/partials/build_list.html#L39

The reason is that there are `Build` objects that don't have a `Version` attached to it. This is because when a `Version` object is deleted, the builds associated to them are not deleted: https://github.com/readthedocs/readthedocs.org/blob/80271b3c0fb424082f9919a24dd89f6373fa13fc/readthedocs/builds/models.py#L714

**Comment by humitos** [comment]
This is how it looks this list now. We may need to do some extra work now to display them in a better way cc @agjohnson 

![Image](https://github.com/user-attachments/assets/49cd6587-a68a-40fe-96b5-d66f8ad983a2)

**Comment by humitos** [comment]
This is another example



![Image](https://github.com/user-attachments/assets/234c81c0-d4c5-45da-9049-9e5b15b4ed6c)

**Comment by humitos** [comment]
It seems we are still hitting this issue in other places: https://read-the-docs.sentry.io/issues/5690482287/?project=161479&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by humitos** [comment]
The same user hit this again 🙃 , https://read-the-docs.sentry.io/issues/5608420288/?project=161479&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=5

**Comment by agjohnson** [comment]
This is on the dashboard, it looks like a different issue entirely maybe. The dashboard is loading now for the user, so I don't know exactly how to test this though.

This event is on `/dashboard/` and would have been the included build chip template. However, there is logic around the chip to avoid displaying the chip if there is no associated build:

https://github.com/readthedocs/ext-theme/blob/c6c883cabe4496e738149ed00a377c7266b05874/readthedocsext/theme/templates/projects/partials/project_list.html#L95-L99

So with `has_good_build` and `get_latest_build`, how are we passing a `build` to the build chip template where `build.project.pk` and `build.pk` are both none? I'm guessing the fact that this is a translation is a clue. Is it possible there is a timing issue as a project is created and before the build finishes?

**Comment by humitos** [comment]
> So with `has_good_build` and `get_latest_build`, how are we passing a `build` to the build chip template where `build.project.pk` and `build.pk` are both none?

I think what could be happening here is that `has_good_build` is returning `True`, but `get_latest_build` is returning `None`. We should probably put `get_latest_build` in the `if` condition as well.

https://github.com/readthedocs/readthedocs.org/blob/9ef753323822eafdd9c72cb57e6f2ef6b60b305e/readthedocs/projects/models.py#L1022-L1038

**Comment by agjohnson** [comment]
Yeah, that we my guess as well and the fix that I added. :+1:

I don't have any proof of this though, besides the null arguments passed in to the `url` tag. :shrug:

**Comment by agjohnson** [comment]
I tried the projects from the reporting user and the list and detail views look correct now. Still haven't been able to reproduce the error on the project listing view though, but I think we can mark these resolved.
