### ISSUE TITLE
Social signup page is missing porting over

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#420]
This page is shown after you sign up with a social account and auto signup isn't enabled, or it wasn't possible.

![Screenshot 2024-07-10 at 18-01-37 Signup - Read the Docs](https://github.com/readthedocs/ext-theme/assets/4975310/54df41c1-8673-4334-a120-9ce9c130bd48)

This page https://github.com/pennersr/django-allauth/blob/main/allauth/templates/socialaccount/signup.html

**Comment by agjohnson** [comment]
I missed this issue but caught this in my own testing and resolved with #478
