### ISSUE TITLE
Email verifycation template is not styled

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#435]
It seems we are using a default allauth template. This one in particular: https://github.com/pennersr/django-allauth/blob/301324e3ed2bf7c95987f24625ee8ebd7480ce85/allauth/templates/account/verification_sent.html

I think we want to override them to:

- Add an email icon (similar to our "Verify email" template shown when the user clicks the link from the email): https://github.com/readthedocs/ext-theme/blob/790e59de6c0e2a82a9df026a7553470c384bc49f/readthedocsext/theme/templates/account/email_confirm.html#L10-L13
- Don't use title case

![Screenshot_2024-07-25_17-50-58](https://github.com/user-attachments/assets/4e03f5e7-de3d-479d-87f3-556e267686ff)

**Comment by humitos** [comment]
Our looks like:

![Screenshot_2024-07-25_17-52-13](https://github.com/user-attachments/assets/8659b810-1725-44dc-a3af-d7a237afb4ad)

**Comment by agjohnson** [comment]
You know, I have noticed a lot of regressions on allauth templates that look like this too. I wonder if we lost something in an upgrade. I know this is just a missing template that needs added, but I've seen this fairly broken styling on a number of allauth views lately.

I opened up #462 to investigate. Maybe I'm wrong though.

**Comment by agjohnson** [comment]
Just a note, on the examples above, the first template is missing, the second template is the one that users see after clicking the email verification email they are sent, so is a separate template.
