### ISSUE TITLE
2FA: implement templates

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#443]
Allauth provides some templates for 2FA, but they don't look great with the new theme, and some are very simple.

Some examples:

![Screenshot 2024-08-08 at 11-12-26 Two-Factor Authentication - Read the Docs](https://github.com/user-attachments/assets/f65ee050-807b-4c7a-bfc1-a9685c6a9f4f)
![Screenshot 2024-08-08 at 11-11-51 Sign In - Read the Docs](https://github.com/user-attachments/assets/1cd4c3ab-8de3-45bf-b0f4-fa5069477ec3)

The templates that we need to override are (the html files only):

- https://github.com/pennersr/django-allauth/tree/64.0.0/allauth/templates/mfa/recovery_codes
- https://github.com/pennersr/django-allauth/tree/64.0.0/allauth/templates/mfa/totp
- https://github.com/pennersr/django-allauth/tree/64.0.0/allauth/templates/mfa

The templates under webauthn we can ignore, since we aren't using that feature.

ref https://github.com/readthedocs/readthedocs.org/pull/11524

**Comment by agjohnson** [comment]
Those don't look horrible, actually. They will need a pass to clean up though.

The base template allauth uses is maybe a little off. I thought I had tuned that template more, but all of the templates from allauth look like a bit more unstyled than they might have been.
