### ISSUE TITLE
Projects: new regression on project listing response time

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#463]
It looks like it's the build or version query on the project listing now. If you look at the SQL queries in the prod debug instance, you'll see a couple build queries taking the most time now.

Here's an explain:

```
QUERY PLAN
Sort  (cost=4797211.16..4797758.59 rows=218972 width=336) (actual time=5702.557..5702.562 rows=15 loops=1)
  Sort Key: builds_build.date DESC
  Sort Method: quicksort  Memory: 37kB
  ->  Hash Left Join  (cost=215123.68..4710426.92 rows=218972 width=336) (actual time=5512.958..5702.524 rows=15 loops=1)
        Hash Cond: (builds_build.version_id = builds_version.id)
        Filter: (((builds_version.type)::text <> 'external'::text) OR (builds_version.type IS NULL))
        ->  Index Scan using builds_build_project_id on builds_build  (cost=0.56..4455549.77 rows=228962 width=336) (actual time=2.628..4028.505 rows=15 loops=1)
              Index Cond: (project_id = ANY ('{487639,689368,74581,815321,256207,714226,521174,24458,170010,613422,451683,17662,233368,527062,489923}'::integer[]))
              Filter: (SubPlan 1)
              Rows Removed by Filter: 442104
              SubPlan 1
                ->  Limit  (cost=0.99..13.49 rows=1 width=12) (actual time=0.008..0.008 rows=1 loops=442119)
                      ->  Nested Loop Left Join  (cost=0.99..9109.11 rows=729 width=12) (actual time=0.008..0.008 rows=1 loops=442119)
                            Filter: (((u1.type)::text <> 'external'::text) OR (u1.type IS NULL))
                            Rows Removed by Filter: 0
                            ->  Index Scan Backward using builds_buil_project_fea68c_idx on builds_build u0  (cost=0.56..2702.59 rows=762 width=16) (actual time=0.006..0.006 rows=1 loops=442119)
                                  Index Cond: (project_id = builds_build.project_id)
                            ->  Index Scan using builds_version_pkey on builds_version u1  (cost=0.43..8.40 rows=1 width=9) (actual time=0.002..0.002 rows=1 loops=464569)
                                  Index Cond: (id = u0.version_id)
        ->  Hash  (cost=147380.72..147380.72 rows=3897072 width=9) (actual time=1568.329..1568.330 rows=3907920 loops=1)
              Buckets: 131072  Batches: 64  Memory Usage: 3517kB
              ->  Seq Scan on builds_version  (cost=0.00..147380.72 rows=3897072 width=9) (actual time=0.007..838.935 rows=3907920 loops=1)
Planning Time: 0.862 ms
Execution Time: 5702.621 ms
```

**Comment by humitos** [comment]
Taking a quick look at it, I'd say we need an index for this filter

```
Filter: (((builds_version.type)::text <> 'external'::text) OR (builds_version.type IS NULL))
```

If I understand correctly, there is when it takes the most time.

**Comment by humitos** [comment]
Do you know what's the code that executes this query? @agjohnson

**Comment by agjohnson** [comment]
I don't, at least not without looking into this more. I wouldn't be surprised if it ended up being triggered from the templates. I wasn't able to replicate this locally, so prod might be the easiest place to try to debug this more.

**Comment by agjohnson** [comment]
Note: I got this from SQL tab debug toolbar.

**Comment by agjohnson** [comment]
I also just noticed a similar *really* slow page load (22s) on the version listing view:

https://app.readthedocs.org/projects/test-builds/?slug=timetest&privacy=&visibility=&sort=

Not sure if that is related yet.

**Comment by humitos** [comment]
> I also just noticed a similar _really_ slow page load (22s) on the version listing view:

Wow! It takes 34s in my case 💣

**Comment by ericholscher** [comment]
Looks like this is what's slow:

>               ->  Seq Scan on builds_version  (cost=0.00..147380.72 rows=3897072 width=9) (actual time=0.007..838.935 rows=3907920 loops=1)

But without knowing the SQL here, it's hard to track down what query this is.

**Comment by ericholscher** [comment]
We're being pretty sloppy with queries in the templates it looks like. We're repeating this query 3 times per version:

```
SELECT ••• FROM "builds_build" WHERE "builds_build"."version_id" = 5536178 ORDER BY "builds_build"."date" DESC LIMIT 1
```

It looks like it's coming from stuff like this:

https://github.com/readthedocs/ext-theme/blob/412951a2cd14dbf9319597a448108b1e1ddad1e3/readthedocsext/theme/templates/builds/partials/version_list.html#L116

Removing that removes 1 query, but we're running the same query 3 times. We should make that query faster though.

**Comment by ericholscher** [comment]
I added an index:

```
CREATE INDEX idx_version_date ON builds_build (version_id, date DESC);
```

**Comment by agjohnson** [comment]
I'm guessing this was why we added prefetching on the old dashboard:

https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/projects/querysets.py#L124

Instead of suffering multiple queries, prefetch might avoid this lookup entirely. I don't know if the above prefetch would be what we need though.

- #61 hinted at this

**Comment by ericholscher** [comment]
The timing issue on https://app.readthedocs.org/projects/test-builds/?slug=timetest&privacy=&visibility=&sort= is fixed. Let me know if there's another URL that shows this issue -- I clicked around in the dashboard and didn't see anything obvious.

**Comment by agjohnson** [comment]
I think it's also worth looking at prefetch queries. The index has made the queries faster but there are still a lot of extraneous queries.

The templates, project listing specifically, are using very benign model methods that should be using prefetched data but these seem to be avoiding the prefetch.

The culprit on the project listing is `Project.has_good_build`, which isn't triggering the prefetched query (I'm guessing because it's filtering `success=True`). This causes 3 additional lookups per table row (45 total). Changing this to `Project.get_latest_build` is effectively close enough logic and removes all these queries.

The version listing isn't prefetching anything and could be.

**Comment by ericholscher** [comment]
Agreed, but if we have specific queries that are slow, I can look into them. IIRC Organization queries were also being slow?

**Comment by agjohnson** [comment]
Yeah, it's still helpful, just noting that the prefetch ultimately helps solve the issues by removing the queries entirely.

The organization permission query is likely some combination of problems.

- https://github.com/readthedocs/readthedocs-corporate/issues/1829

**Comment by ericholscher** [comment]
This is a really useful traceback for the template issue: https://onenr.io/0VRVr3emdRa -- it shows where the time is going inside the template blocks.

**Comment by agjohnson** [comment]
I opened up several PRs here to actually address the queries. I didn't find anything sloppy about queries however. I found the issues were either prefetching was missing or there were small changes to the logic to avoid an extra query.

- #493 
- https://github.com/readthedocs/readthedocs.org/pull/11616
- https://github.com/readthedocs/readthedocs.org/pull/11613
