### ISSUE TITLE
Port or remove footer.html template

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#464]
This template is used by our footer API

https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/api/v2/templates/restapi/footer.html

This template doesn't really make sense to be ported, so I guess we want to remove it? But if we do, that will break our old `footer_html` API, which may be used for old projects for some custom stuff.

ref https://github.com/readthedocs/readthedocs-corporate/pull/1807#discussion_r1729403446

**Comment by humitos** [comment]
I think it's fine deprecating this endpoint and not porting the template. Nobody will be using it after October 7th when addons became the default.
