### ISSUE TITLE
Add project: don't show VCS SSO organization if the user is not the owner

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#466]
I selected an organization with VCS SSO that it seems I'm member of

![Screenshot_2024-08-27_19-19-31](https://github.com/user-attachments/assets/fded2164-0d18-4b99-b07c-2749e33fac0a)

but then I got this error

![Screenshot_2024-08-27_19-19-24](https://github.com/user-attachments/assets/4e419b60-c1a2-43f1-90a6-90dab3fe1e4d)

I suppose we should not show VCS SSO organization in the first selector if we are not the owner. cc @agjohnson thoughts? Do we need to communicate to users that there may be organization that don't appear in the selector because of this reason?

**Comment by agjohnson** [comment]
I might say the same as #467 here and we should show an error/disabled state. I think for now this UX is okay-ish, and agree it would be more confusing for the organization to be missing from the list.
