### ISSUE TITLE
Add project: error on wizard

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#477]
I added a project automatically using this GitLab project https://gitlab.com/humitos/rtd-project-a and got a 500.

Sentry issue: https://read-the-docs.sentry.io/issues/5792086719/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=0

Note that it works on the old dashboard without issues.

**Comment by humitos** [comment]
I tried reproducing this on community and commercial, but I wasn't able to replicate it.

**Comment by humitos** [comment]
I'm not able to reproduce this issue anymore.

**Comment by humitos** [comment]
Meh, it keeps happening because Sentry still reports it, but I'm unable to reproduce it 🤷🏼

**Comment by humitos** [comment]
I guess this is because of some weird usage of the form, maybe because spammers...

**Comment by agjohnson** [comment]
Is this different from #476 ?

- #476

**Comment by humitos** [comment]
I'm not able to reproduce this issue anymore. I've tried adding a GitLab repository on .org and .com.

**Comment by agjohnson** [comment]
Note: this could be going back in the form at config step or something, the `config` key is missing from the form wizard list of forms.

**Comment by ericholscher** [comment]
We think this is a bot doing something hacky, probably not a real issue.

**Comment by humitos** [comment]
I'm going to close it for now. We can come back if we start getting user reports.

**Comment by humitos** [comment]
I got a support request from a user about this: https://app.frontapp.com/open/cnv_ori78av?key=7bu4nReUCopK8_sMwONvi_U05Aw-HHLa

and I was able to reproduce it by following these steps:

1. Go to https://app.readthedocs.org/dashboard/import/manual/
2. Repo name: `whatever`
3. Repository URL: `https://github.com/Mahendra-TitanEd/lms-documentation.git`
4. Default branch: `vic-documentation`
5. Language: `English`
6. Click `Next`
7. Click `This file exists`
8. A 500 error is shown

This is the entry in Sentry: https://read-the-docs.sentry.io/issues/5792086719/events/7a29f1ecc6874b4da1a960dfc364390c/?project=148442&query=is%3Aunresolved%20%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22%20%21message%3A%22frame-ancestors%22&referrer=next-event&statsPeriod=14d&stream_index=0

After testing it, I tried to reproduce it again and I wasn't able to. I'm pretty confused about what's going on here 🤷🏼. @readthedocs/core any of you is able to reproduce it?

**Comment by stsewd** [comment]
This is because form_list is a class attribute, once it's modified by one request, it will be changed for all subsequent requests (requests to the same server anyway). I guess django restarts after a 500, that's why we don't see this more often, you can probably replicate this by importing a project that hits that code twice.
