### ISSUE TITLE
Replace usage of `is_admin:project` filter in object lists

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#49]
I've updated this issue to be more specific. Originally, this was meant as a note from an previous change:

- https://github.com/readthedocs/readthedocs.org/pull/7277/

The original change was to update use of `request.user|is_admin:project` with a context variable `is_project_admin` -- which is the same call and return value, but cached instead of repeated in the template.

However, neither approach is usable when listing multiple projects or similar, where we need the original logic (`request.user|is_admin:project`). We can't use the context variable approach, as this still incurs the same performance issue as doing this in template.

We need another option for iterating over a list of objects and using `is_admin`.

**Comment by agjohnson** [comment]
Note this is not usable in a listing view yet, where I have used `is_admin` the most so far. Noted in #128 but this code is responsible for most of the loading lag on some listing UIs.

**Comment by humitos** [comment]
I think the `is_project_admin` is the wrong approach. It needs to be defined on the context for each view. Besides, it implies rewriting all the templates that are currently using `is_admin:project` to use the new variable from the context.

I'd say we should implement a ~5s cache on `is_admin` filter tag instead (https://github.com/readthedocs/readthedocs.org/blob/5a5bf41db92cca4d14c9657da2e2a6067a8b9b53/readthedocs/core/templatetags/privacy_tags.py#L13-L15). That doesn't need to rewrite anything and all the templates will be benefit immediately without any other change.

I mentioned something similar on the PR linked at (https://github.com/readthedocs/readthedocs.org/pull/7277#discussion_r452072549)

**Comment by agjohnson** [comment]
Mentioned on #128, this approach doesn't quite solve the problem there. I'm not sure a cached admin check is the final solution we want either, but I do agree we should do something other than replace these checks with `is_project_admin` -- which also doesn't work to solve #128.

Ideally:

- Templates and views all use the same approach
- This approach performs well when iterating over multiple objects (project listing view), not just a single object (project detail view)

I'll repurpose this issue to be more clear that perhaps `is_project_admin` is not the best target, but we probably want to do something more than just caching.

**Comment by agjohnson** [comment]
Removed assignment for now, it's looking like this needs to be backend change.

**Comment by agjohnson** [comment]
Just noting that this is mostly to resolve:

#128
