### ISSUE TITLE
Add commit hash to build table

### ISSUE THREAD

**Issue by reece** [readthedocs/ext-theme#5]
It would be very handy for the "Recent Builds" table to indicate the commit hash (or changeset id for hg, etc). Even better would be a link to the commit and the first line of the commit message.

**Comment by agjohnson** [comment]
This has been a feature for a while on our beta dashboard:

https://beta.readthedocs.org/projects/time-test/builds/23581428/

![image](https://github.com/readthedocs/ext-theme/assets/1140183/2abd1ac4-0928-4ce5-9451-c025a6ba3bc7)

This does respect tags as well, but likely falls down a bit on SVN and friends. I don't feel we need to design around these anymore as we are announcing deprecation for support on these tools with

- https://github.com/readthedocs/readthedocs.org/issues/8840
