### ISSUE TITLE
Update 2fa templates

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#501]
There was a new release of allauth that updates some (3) templates. We need to update ours to match those changes.

- Reference: https://github.com/readthedocs/readthedocs.org/pull/11625#discussion_r1780817896

**Comment by stsewd** [comment]
We need to unpin allauth after this is done

**Comment by agjohnson** [comment]
I believe I already implemented all of these, I didn't see this issue but think this covers this:

- #480 

The only thing I didn't implement yet is a link to the main view from the admin nav. Once we're tested this can be added.

**Comment by stsewd** [comment]
This is related to a new change in allauth, mainly from this PR https://codeberg.org/allauth/django-allauth/pulls/4111/files
